#Array Indexing

Indexing means:
Finding value using position

Important:
Python starts from 0

Example:

In [ ]:
import numpy as np

In [2]:
arr = np.array([10,20,30,40])
arr

array([10, 20, 30, 40])

In [3]:
arr[0]

np.int64(10)

Negative Indexing

Count from end:
10 20 30 40
-4 -3 -2 -1

In [4]:
arr[-1]

np.int64(40)

#2D Indexing

#array[row,column]

In [6]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])

arr[1,2]

np.int64(6)

#3D Indexing

#array[block,row,column]

In [7]:
arr = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

arr[1,0,1]

np.int64(6)

#Array Slicing /
Slicing = taking part of an array
Syntax: [start:end]

In [8]:
arr = np.array([10,20,30,40,50])

arr[1:4]

array([20, 30, 40])

Slice till beginning

In [9]:
arr[:3]

array([10, 20, 30])

Slice till end

In [10]:
arr[2:]

array([30, 40, 50])

Step slicing

In [11]:
arr[::2]

array([10, 30, 50])

Reverse Array

In [12]:
arr[::-1]

array([50, 40, 30, 20, 10])

2D Slicing

Format:array[row_slice,column_slice]

In [13]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
arr[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

Array Looping

Looping means: Visit every element one by one.

In [14]:
arr = np.array([10,20,30])

for i in arr:
    print(i)

10
20
30


Loop in 2D Array

In [15]:
arr = np.array([
    [1,2],
    [3,4]
])

for row in arr:
    print(row)

[1 2]
[3 4]


Inner loop

In [16]:
for row in arr:
    for item in row:
        print(item)

1
2
3
4


NumPy Special Loop → ndenumerate()

Very useful.

Gives:index + value

In [17]:
for index, value in np.ndenumerate(arr):
    print(index, value)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


iter() and enumerate()

iter()

Gets values one by one.

In [18]:
arr = np.array([10,20,30])

x = iter(arr)

print(next(x))
print(next(x))

10
20


enumerate()

Gets:

index + value

In [19]:
for i, j in enumerate(arr):
    print(i, j)

0 10
1 20
2 30


Array Sorting

Sorting = arranging order.

Ascending

In [20]:
arr = np.array([40,10,30,20])

print(np.sort(arr))

[10 20 30 40]


Descending

In [21]:
print(np.sort(arr)[::-1])

[40 30 20 10]


Sort String

In [27]:
arr1 = np.array(["mango","apple"])

np.sort(arr1)

array(['apple', 'mango'], dtype='<U5')

Fancy Indexing

Fancy indexing means:

Selecting multiple indexes together.

Normal indexing:

In [28]:
arr[1]

np.str_('apple')

Fancy indexing:

In [29]:
arr[[0,1,1]]

array(['mango', 'apple', 'apple'], dtype='<U5')

In [30]:
arr = np.array([10,20,30,40,50])

arr[[0,2,4]]

array([10, 30, 50])

Fancy Indexing in 2D

In [31]:
arr = np.array([
    [1,2],
    [3,4],
    [5,6]
])

arr[[0,2]]

array([[1, 2],
       [5, 6]])

Boolean Indexing

Boolean means:

True / False

Used for filtering data.

Very important for Data Analyst work.

In [32]:
arr = np.array([10,20,30,40,50])

arr > 25

array([False, False,  True,  True,  True])

Filter values

In [33]:
arr[arr > 25]

array([30, 40, 50])

Even Numbers

In [34]:
arr[arr % 2 == 0]

array([10, 20, 30, 40, 50])

Greater than condition

In [35]:
arr = np.array([5,10,15,20])

arr[arr >= 10]

array([10, 15, 20])

Golden Memory Tricks

Indexing → one value
Slicing → many continuous values
Fancy indexing → many selected values
Boolean indexing → filtered values
Looping → visit all values
Sorting → arrange values

Quick Revision Table
Topic	            Meaning
Indexing	        Get one value using position
Slicing	            Get part of array
Looping	            Visit values one by one
iter()	            Take next item
enumerate()	        Get index + value
Sorting	            Arrange order
Fancy Indexing	    Get multiple indexes
Boolean Indexing	Filter using condition