1. Copy in NumPy
What is Copy?

A copy creates a completely new array.

If you change the copied array, the original array does not change.

In [2]:
import numpy as np

a = np.array([1, 2, 3, 4])

b = a.copy()

b[0] = 100

print(a)
print(b)

[1 2 3 4]
[100   2   3   4]


Explanation:
b = a.copy() creates a separate array
Changing b will not affect a

Think like this:

Copy = Xerox copy /
Changing xerox paper won't affect original paper.

2. View in NumPy
What is View?

A view shares memory with the original array.

If you change one, the other also changes.

Example:

In [2]:
a = np.array([10, 20, 30])

b = a.view()

b[0] = 999

print(a)
print(b)

[999  20  30]
[999  20  30]


Explanation:

view() does not create new memory.

Think like:

View = Mirror /
Change original → reflection changes.

Difference Between Copy and View
Copy	          View
New memory	      Same memory
Original          won't change	Original changes
Independent	      Connected

3. Flatten
What is flatten()?

Converts multi-dimensional array into 1D array.

It creates a copy.

Example:

In [3]:
a = np.array([[1,2],
              [3,4]])

b = a.flatten()

print(b)

[1 2 3 4]


Important:

flatten() = copy

Changing flattened array won't affect original.

In [4]:
b[0] = 100

print(a)

[[1 2]
 [3 4]]


No change.

4. Ravel
What is ravel()?

Also converts array into 1D.

But it returns a view (mostly).

Example:

In [5]:
a = np.array([[1,2],
              [3,4]])

b = a.ravel()

b[0] = 100

print(a)

[[100   2]
 [  3   4]]


Difference:
flatten() → copy
ravel() → view

flatten vs ravel
flatten()	          ravel()
Copy	              View
More memory	          Less memory
Original unchanged	  Original may change

5. Reshape
What is reshape()?

Changes shape of array.

Example:

1D → 2D

In [6]:
a = np.array([1,2,3,4,5,6])

b = a.reshape(2,3)

print(b)

[[1 2 3]
 [4 5 6]]


Explanation:

(2,3) means:

2 rows
3 columns

Rule:

Total elements must match.

Correct: 6 elements = 2 × 3
Wrong: a.reshape(4,4)
Error because: 6 ≠ 16

Using -1

NumPy automatically calculates.

In [7]:
a.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

6. Transpose
What is transpose?

Converts:

Rows → Columns
Columns → Rows

Example:

In [8]:
a = np.array([[1,2,3],
              [4,5,6]])

a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

Before: 2 × 3

After transpose: 3 × 2

Shortcut: a.T or a.transpose()

7. Broadcasting
What is Broadcasting?

NumPy automatically stretches smaller arrays to match bigger arrays.

Example 1:

In [9]:
a = np.array([1,2,3])

a + 10

array([11, 12, 13])

Here NumPy treats: 10 → [10,10,10]

Example 2:

In [10]:
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([10,20,30])

a + b

array([[11, 22, 33],
       [14, 25, 36]])

NumPy stretches b:

[10,20,30]

to

[[10,20,30],
 [10,20,30]]

This is broadcasting.

8. Arithmetic Operations

NumPy supports math directly.

Addition

In [11]:
a = np.array([1,2,3])
b = np.array([4,5,6])

a+b

array([5, 7, 9])

Subtraction
a-b
Multiplication
a*b

Element-wise multiplication.

Division
a/b
Power
a**2

9. Variance
What is Variance?

Measures how spread out values are from mean.

Formula idea:

Difference from mean → square → average.

Example:

In [12]:
a = np.array([10,20,30,40])

np.var(a)

np.float64(125.0)

Meaning:

Higher variance = data spread more.

Lower variance = data close together.

10. Standard Deviation
What is Standard Deviation?

Square root of variance.

Shows spread in easier units.

Example:

In [14]:
np.std(a)

np.float64(11.180339887498949)

Formula relation:

σ=
Variance
	​


11. Unique
What is unique()?

Removes duplicates.

Example:

In [15]:
a = np.array([1,2,2,3,3,4,5])
np.unique(a)

array([1, 2, 3, 4, 5])

Used a lot in data cleaning.

12. Percentile
What is Percentile?

Tells where a value lies in data.

Example:

50th percentile = median
25th percentile = lower quarter
75th percentile = upper quarter
Example:

In [16]:
a = np.array([10,20,30,40,50])
np.percentile(a,50)

np.float64(30.0)

More Example:

In [17]:
np.percentile(a,25)

np.float64(20.0)

13. Sum
What is sum()?

Adds all values.

Example:

In [18]:
a = np.array([10,20,30])

np.sum(a)

np.int64(60)

Sum in 2D Array

In [19]:
a = np.array([[1,2],
              [3,4]])

np.sum(a)

np.int64(10)

Axis in Sum

Row-wise:

In [20]:
np.sum(a, axis=1)

array([3, 7])

Column-wise:

In [21]:
np.sum(a, axis=0)

array([4, 6])

Quick Revision Table
Topic	             Meaning
copy()	             Separate array
view()	             Shared memory
flatten()	         2D → 1D copy
ravel()	             2D → 1D view
reshape()	         Change shape
transpose()     	 Row ↔ Column
broadcasting	     Auto matching shapes
arithmetic ops	     + − * /
variance	         Data spread
std	                 Square root of variance
unique()	         Remove duplicates
percentile()	     Data position
sum()	             Add elements