1. Identity Matrix

An identity matrix is a matrix where:

diagonal = 1
remaining places = 0

Example (3×3):
1 0 0
0 1 0
0 0 1

In [1]:
import numpy as np

i = np.identity(3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

You can also use: np.eye(3)
Same output.

Why called identity?

Because multiplying any matrix with identity gives the same matrix.

Example:

In [2]:
A = np.array([[1,2],
              [3,4]])

I = np.identity(2)

A@I

array([[1., 2.],
       [3., 4.]])

A × I = A

2. A Inverse Matrix (A⁻¹)

Inverse means opposite matrix.

Formula idea:

If A × A⁻¹ = I

then A⁻¹ is inverse of A.

Example matrix:

In [3]:
A = np.array([[1,2],
              [3,4]])
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [7]:
A = np.array([[1,2],
              [3,4]])
A @ np.linalg.inv(A)

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

That is identity matrix.

So: A × A⁻¹ = I

3. I Inverse (I⁻¹)

If you mean identity matrix inverse, then:

The inverse of identity matrix is identity itself.

Because: I × I = I

In [8]:
I = np.identity(3)

np.linalg.inv(I)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Same matrix.

So: I⁻¹ = I

4. Determinant Matrix

Determinant gives a single number from a square matrix.

Formula idea for 2×2 matrix:

For
A=[ a b ]
  [ c d ]
Determinant is:
∣A∣=ad−bc
Example:

In [9]:
A = np.array([[1,2],
              [3,4]])

np.linalg.det(A)

np.float64(-2.0000000000000004)

Calculation:

(1×4) - (2×3)
= 4 - 6
= -2

Important Rule

Inverse exists only if determinant ≠ 0

Example:

In [10]:
A = np.array([[1,2],
              [2,4]])
np.linalg.det(A)

np.float64(0.0)

In [11]:
Now inverse:
A = np.array([[1,2],
              [2,4]])
np.linalg.inv(A)

SyntaxError: invalid syntax (1685618223.py, line 1)

Matrix Concept	     NumPy Function
Identity Matrix	     np.identity(n) or np.eye(n)
Inverse Matrix	     np.linalg.inv(A)
Determinant	         np.linalg.det(A)
Matrix Multiply	     @ or np.dot()