In NumPy, matrix functions are mainly available in:

numpy.linalg

linalg means Linear Algebra (matrix mathematics).

1. Matrix (2D Array) in NumPy

Before learning matrix functions, understand what a matrix is.

A matrix is simply a 2D array (rows and columns).

Example:

In [1]:
import numpy as np

a = np.array([[1, 2],
              [3, 4]])

a

array([[1, 2],
       [3, 4]])

here:

Row = horizontal
Column = vertical

This is a 2×2 matrix

Because:

2 rows
2 columns

2. Identity Matrix

An identity matrix is a square matrix where:

Diagonal values = 1
Other values = 0

Example:

[[1 0]
 [0 1]]

Think of it like number 1 in multiplication.

Example:

In [2]:
b = np.identity(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Explanation:

3 means create a 3×3 identity matrix

Another way:

np.eye(3)

Same output.

3. Matrix Transpose

Transpose means:

➡️ Rows become columns
➡️ Columns become rows

Example matrix:

[[1, 2],
 [3, 4]]

After transpose:

[[1, 3],
 [2, 4]]

In [3]:
a = np.array([[1,2],
              [3,4]])

a.T

array([[1, 3],
       [2, 4]])

Easy Trick:

Transpose = flip across diagonal

4. Matrix Addition

Add corresponding elements.

Example:

Matrix A:

[[1,2],
 [3,4]]

Matrix B:

[[5,6],
 [7,8]]

Addition:

[[6,8],
 [10,12]]

In [4]:
a = np.array([[1,2],
              [3,4]])

b = np.array([[5,6],
              [7,8]])

a+b

array([[ 6,  8],
       [10, 12]])

Condition: Same shape required

5. Matrix Subtraction

Same concept.

Code:

In [5]:
a-b

array([[-4, -4],
       [-4, -4]])

6. Matrix Multiplication

This is important.

There are 2 types:

Type 1: Normal Multiplication

Element-by-element multiplication.

In [6]:
a*b

array([[ 5, 12],
       [21, 32]])

Because:

1×5 = 5
2×6 = 12
3×7 = 21
4×8 = 32

Type 2: Matrix Multiplication (Real Matrix Math)

Use: np.dot() or @

Example:

In [7]:
a = np.array([[1,2],
              [3,4]])

b = np.array([[5,6],
              [7,8]])

np.dot(a,b)

array([[19, 22],
       [43, 50]])

How?

First row × first column:

(1×5) + (2×7)
= 5 + 14
= 19

First row × second column:

(1×6) + (2×8)
= 6 + 16
= 22

Like that all values are calculated.

Shortcut:

print(a @ b)

Same output.

7. Determinant of Matrix

Determinant tells whether matrix can have inverse or not.

Function:

np.linalg.det()

Example

In [9]:
a = np.array([[1,2],
              [3,4]])

np.linalg.det(a)

np.float64(-2.0000000000000004)

Important Rule:

If determinant = 0

Inverse cannot be found.

If determinant ≠ 0

Inverse possible.

8. Matrix Inverse

Inverse means reverse matrix.

Function:

np.linalg.inv()

Example:

In [10]:
a = np.array([[1,2],
              [3,4]])
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

Easy Understanding:

Inverse is like division in matrix.

Example:

A × A⁻¹ = Identity Matrix

Means:

[[1,0],
 [0,1]]

Code:

In [11]:
a = np.array([[1,2],
              [3,4]])

inverse = np.linalg.inv(a)

a @ inverse

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

This is identity matrix.

9. Matrix Power

Raise matrix to power.

Function:

np.linalg.matrix_power()

Example:

In [12]:
a = np.array([[1,2],
              [3,4]])

np.linalg.matrix_power(a,2)

array([[ 7, 10],
       [15, 22]])

Means:

A × A

If:

3

Means:

A × A × A

10. Rank of Matrix

Rank tells:

➡️ Number of independent rows or columns.

Function:

np.linalg.matrix_rank()

Example:

In [13]:
a = np.array([[1,2],
              [3,4]])

np.linalg.matrix_rank(a)

np.int64(2)

Most Important for Beginners

Focus first on:

Identity matrix
Transpose
Matrix multiplication
Determinant
Inverse matrix
Trace

These are usually explained first in class.

Also remember:

❌ identity, inverse, determinant are not separate keywords

✅ They are NumPy functions

Example:

np.identity()
np.linalg.inv()
np.linalg.det()