1. randint() → Random Integer
Meaning:

randint() gives random whole numbers (integers).

Think of it like:

"Pick a random number between these values."

Syntax: np.random.randint(start, end)

start → where number starts
end → where number stops (end is excluded)

In [3]:
import numpy as np

x = np.random.randint(1, 10)
x

9

Explanation:

It picks a random number from:

1,2,3,4,5,6,7,8,9

10 will not come because ending number is excluded.

Example 2: Multiple Numbers

In [4]:
x = np.random.randint(1, 10, 5)
x

array([1, 5, 2, 4, 7], dtype=int32)

Explanation:

Here:5

means generate 5 random numbers.

Example 3: 2D Array

In [6]:
x = np.random.randint(1, 100, (2,3))
x

array([[46,  4, 93],
       [61, 97, 68]], dtype=int32)

Explanation:

Creates:

2 rows
3 columns

with random numbers.

2. random() → Random Decimal Number
Meaning: Generates random decimal values (float) between: 0 and 1
Syntax:
np.random.random()

Example 1

In [7]:
x = np.random.random()
x

0.569073742194726

Explanation:

Always gives decimal number between: 0 to 1

Example 2: Multiple Values

In [8]:
x = np.random.random(5)
x

array([0.8293692 , 0.78954051, 0.54688003, 0.43508915, 0.58704728])

Explanation:

Generates 5 random decimal numbers.

Example 3: Matrix

In [9]:
x = np.random.random((2,3))
x

array([[0.50611384, 0.31085772, 0.32760881],
       [0.30574342, 0.5020347 , 0.42987948]])

In [ ]:
Easy Difference: randint() vs random()
Function	Gives
randint()	Whole numbers
random()	Decimal numbers

3. choice() → Pick Random Item
Meaning:

Selects a random item from a list/array.

Think:

"Choose one random thing."

Syntax: np.random.choice(list)

Example 1

In [10]:
a = np.random.choice([10,20,30,40])
a

np.int64(20)

Explanation:

It randomly selects one value from the list.

Example 2: Choosing Multiple Items

In [11]:
b = np.random.choice([10,20,30,40], 3)
b

array([10, 20, 30])

Explanation:

Picks 3 random items.

Real-Life Example:

Imagine lottery:

In [12]:
students = ["A","B","C","D"]

winner = np.random.choice(students)
winner

np.str_('C')

4. shuffle() → Mix/Change Order
Meaning:

shuffle() changes the order of elements randomly.

Think:

"Mix the cards."

Syntax: np.random.shuffle(array)

Example

In [13]:
x = np.array([1,2,3,4,5])

np.random.shuffle(x)

x

array([4, 2, 1, 3, 5])

Explanation:

Same numbers exist.

But order changes.

5. seed() → Fixed Random Output

This is VERY IMPORTANT and many beginners get confused.

Problem Without Seed

Normally random values change every time.

Example: 

In [15]:
print(np.random.randint(1,10))

2


What seed() Does

seed() fixes the randomness.

It gives same output every time.

Syntax:
np.random.seed(number)

Example:

In [20]:
np.random.seed(1)

print(np.random.randint(1,10))

6


Same result!

Another Example:

In [21]:
np.random.seed(10)

print(np.random.randint(1,100,5))

[10 16 65 29 90]


Same output whenever you run.

Why Use Seed?

Used when:

1. Testing code

You want same results every time.

2. Data Science / Machine Learning

To reproduce results.

Example:

Without seed: different output

With seed: same output

Super Easy Memory Trick
randint()

👉 Random Integer

(integer = whole number)

random()

👉 Random decimal

(0 to 1)

choice()

👉 Choose random item

shuffle()

👉 Shuffle / mix order

seed()

👉 Fix randomness

(same output every time)

Quick Revision Code

In [22]:
import numpy as np

# randint
print(np.random.randint(1,10,5))

# random
print(np.random.random(5))

# choice
print(np.random.choice([10,20,30,40],2))

# shuffle
x = np.array([1,2,3,4,5])
np.random.shuffle(x)
print(x)

# seed
np.random.seed(1)
print(np.random.randint(1,10))

[1 2 9 1 9]
[0.15037787 0.68381843 0.81660184 0.33607158 0.89081653]
[30 30]
[5 3 4 1 2]
6


Task:

1.Find the average by students and subject

In [35]:
np.random.seed(1)
marks = np.random.randint(20,100,(10,5))
marks

array([[57, 32, 92, 29, 95],
       [25, 99, 84, 36, 21],
       [96, 91, 26, 45, 70],
       [40, 38, 31, 48, 49],
       [34, 70, 88, 33, 29],
       [27, 83, 81, 42, 77],
       [21, 20, 80, 28, 33],
       [67, 92, 50, 91, 23],
       [90, 41, 69, 77, 23],
       [88, 44, 63, 96, 46]], dtype=int32)

axis=0 → subject (column)
axis=1 → student (row)

In [36]:
# Average by students (row-wise)
student_avg = np.mean(marks, axis=1)

# Average by subjects (column-wise)
subject_avg = np.mean(marks, axis=0)

print("Student Average:")
print(student_avg)

print("\nSubject Average:")
print(subject_avg)

Student Average:
[61.  53.  65.6 41.2 50.8 62.  36.4 64.6 60.  67.4]

Subject Average:
[54.5 61.  66.4 52.5 46.6]


2.Find highest and lowest per subject

In [40]:
# Highest mark per subject
highest_mark = np.max(marks, axis=0)

# Lowest mark per subject
lowest_mark = np.min(marks, axis=0)

print("Highest mark per subject:")
print(highest_mark)

print("\nLowest mark per subject:")
print(lowest_mark)

Highest mark per subject:
[96 99 92 96 95]

Lowest mark per subject:
[21 20 26 28 21]


3.Find which student is overall class topper

In [49]:
#sum of all student marks
std_total = np.sum(marks, axis=1)
std_total

#overall class topper
cls_topper = np.max(std_total)
cls_topper

np.int64(337)

4.Find the total students have passed by counting the subject 

In [59]:
# count students passed in each subject
pass_count = np.sum(marks >= 36, axis=0)
pass_count

# display result
for i, count in enumerate(pass_count, start=1):
    print(f"Subject {i} {count} students passed")

Subject 1 6 students passed
Subject 2 8 students passed
Subject 3 8 students passed
Subject 4 7 students passed
Subject 5 5 students passed


5.Find which subject is difficult?

In [58]:
#count stuidents fail in particular subeject
fail_count = np.sum(marks <= 35, axis=0)
fail_count

#display result
for i, count in enumerate(fail_count, start=1):
    print(f"subject {i} {count} students failed")

# find difficult subject
difficult_subject = np.argmax(fail_count)

print(f"Most difficult subject is Subject {difficult_subject + 1}")

subject 1 4 students failed
subject 2 2 students failed
subject 3 2 students failed
subject 4 3 students failed
subject 5 5 students failed
Most difficult subject is Subject 5


6.Rank the students by their total marks?

In [66]:
#ranking (indices sorted by marks)
rank = np.argsort(std_total)[::-1]
rank

#display ranking
for rank, i in enumerate(rank, start=1):
    print(f"Rank {rank} Student {i+1} with {std_total[i]} marks")

Rank 1 Student 10 with 337 marks
Rank 2 Student 3 with 328 marks
Rank 3 Student 8 with 323 marks
Rank 4 Student 6 with 310 marks
Rank 5 Student 1 with 305 marks
Rank 6 Student 9 with 300 marks
Rank 7 Student 2 with 265 marks
Rank 8 Student 5 with 254 marks
Rank 9 Student 4 with 206 marks
Rank 10 Student 7 with 182 marks
